[server]
headless = true
# port = 7860
enableCORS = false 

[theme]
base = "dark"
primaryColor = "#4A90E2"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor = "#E2E8F0"
font = "sans serif"